calyx-servicios/custom-etilfarma

purchase_order_foreign_report/report/purchase_order_foreign_template.xml
Incidence nbr./s.: ODOO-519.
- Update foreign report template to show city.
=> [UPD] [purchase_order_foreign_report]

foreign_purchase_order/README.rst, foreign_purchase_order/__manifest__.py, foreign_purchase_order/models/account_invoice.py
Incidence nrb./s.: ODOO-672
- Overwrite "onchange_document_number" function to add if statement.
=> [UPD] [foreign_purchase_order] ODOO-672

foreign_purchase_lines/__manifest__.py, foreign_purchase_lines/i18n/es_AR.po, foreign_purchase_lines/models/purchase_order_line.py, foreign_purchase_lines/views/purchase_order_view.xml, purchase_order_invoice_to/views/purchase_order_view.xml
Incidences nrb.s/: ODOO-749, ODOO-953, ODOO-957:
-  Update manifest, module version.
-  New "product_id_default_code" field in purchase_order_line.
-  Clean code in purchase_order_line.
-  Add and hide fields in purchase_order_form view.
-  Views and translations
=> [UPD][purchase_invoice_tp][foreign_purchase_lines] ODOO-749, ODOO-953, ODOO-957:

foreign_purchase_order/i18n/es_AR.po, foreign_purchase_order/models/purchase_order.py, foreign_purchase_order/views/purchase_order_view.xml
Incidence nbr./s.: ODOO-1376.
- Add status column
- Views and translations
=> [UPD][foreign_purchase_order]

foreign_purchase_order/__manifest__.py, foreign_purchase_order/static/src/css/foreign_purchase_order.css, foreign_purchase_order/views/assets.xml, foreign_purchase_order/views/purchase_order_view.xml, purchase_order_invoice_to/models/purchase_order.py, purchase_order_invoice_to/views/purchase_order_view.xml
Incidence nbr./s.: ODOO-1375.
Add css to list view.
=> [ADD][foreign_purchase_order_invoice_to]

foreign_purchase_order/i18n/es_AR.po, foreign_purchase_order/models/purchase_order.py, foreign_purchase_order/views/purchase_order_view.xml
Incidence nbr./s.: ODOO-1384.
- Add field
- Views and translations
=> [ADD][foreign_purchase_order]

purchase_order_invoice_to/i18n/es_AR.po, purchase_order_invoice_to/views/purchase_order_view.xml
Incidence nbr./s.: ODOO-1377
- Modify button_confirm_third_party string
- Modify related translation
=> [FIX][purchase_order_invoice_to confirm button]

purchase_order_invoice_to/models/purchase_order.py
=> [FIX][purchase_order_invoice_to]

purchase_order_foreign_report/data/mail_template_data.xml, purchase_order_foreign_report/data/mail_template_data_impo.xml
[ADD][purchase_order_foreign_report]
Incidence nbr./s.: ODOO-1368.
- Add templates
=> [ADD][purchase_order_foreign_report]

etilfarma_translations_fixes/i18n/es_AR.po, foreign_purchase_order/i18n/es_AR.po, purchase_order_booking_email/i18n/es_AR.po, purchase_order_marks/l18n/es_AR.po
…rder_booking_email][purchase_order_marks]
Incidence nbr./s.: ODOO-734.
- Add translations
=> [UPD][etilfarma_translation_fixes][foreign_purchase_order]... ODOO-734

foreign_trade/l18n/es_AR.po, foreign_trade/models/sale_order.py, foreign_trade/report/sale_order_template.xml, foreign_trade/views/sale_order_view.xml
Incidence nbr./s.: ODOO-1423. ODOO-1424.
- Add customer purchase order field
- Add field to reports
- Views and translations
=> [ADD][foreign_trade]

foreign_purchase_order/i18n/es_AR.po
Incidence nbr./s.: ODOO-734
-add Date Picker translation
=> [UPD][foreign_purchase_order]ODOO-734

foreign_trade/l18n/es_AR.po
Add foreign_trade Translations. Odoo-893
=> 11.0 ODOO-893 translations

foreign_trade/models/sale_order.py
[FIX][foreign_trade] 
Now when you confirm a sale order it wont reserve products automatically
=> [FIX][foreign_trade] 

foreign_trade/report/sale_order_template.xml
Incidence nbr./s.: ODOO-1617.
- Modifications in sales report
=> [UPD][foreign_trade]

foreign_purchase_lines/i18n/es_AR.po, foreign_purchase_lines/models/product_template.py, foreign_purchase_lines/models/purchase_order_line.py, foreign_purchase_lines/views/product_template_view.xml, foreign_trade/models/sale_order_line.py, foreign_trade/report/sale_order_template.xml, foreign_trade/views/sale_order_view.xml
Incidence nbr./s.: ODOO-1619.
- Add fields to report
- Views and translations
=> [ADD][foreign_trade][foreign_purchase_lines]

purchase_request_extension/models/purchase_request.py
=> [FIX][Purchase_request_extension]

foreign_purchase_order/i18n/es_AR.po, purchase_order_terms_to_tracing/l18n/es_AR.po
-Modified translation files in both modules
=> [UPD][foreign_purchase_order][purchase_order_terms_to_tracing]ODOO-1735

foreign_trade/views/sale_order_view.xml
Incidence nbr./s.: ODOO-1618.
- modified sale_order_view_xml. Hides product_nmc(HS_Code) if order_type is not foreign
=> [UPD][foreign_trade] ODOO-1618

stock_move_lines/__manifest__.py, stock_move_lines/i18n/es_AR.po, stock_move_lines/models/stock_move_line.py, stock_move_lines/views/stock_move_line_view.xml
Add button to stock_move_lines to link movements to their respective purchase or sale order
=> 11.0 stock move lines hyperlink ODOO-1684

foreign_trade/views/packing_list_report.xml
Added footer to Packing list report (ES & EN)
=> 11.0 upd packing list report ODOO-1759

foreign_purchase_order/views/purchase_order_view.xml
-Never use ilike in attrs because they are not supported
=> [FIX][foreign_purchase_order]

foreign_trade/models/sale_order_line.py, foreign_trade/report/sale_order_template.xml
[UPD][foreign_trade]
Incidence nbr./s.: ODOO-1737.
- Add order date field to report
- Modify internal reference field
=> 11.0 order date in report

foreign_trade/i18n/es_AR.po, foreign_trade/models/sale_order.py, foreign_trade/views/sale_order_view.xml
ODOO-1847
Changed translations folder name l18n -> i18n (why translations made weren't being applied)
Deleted leftover merge conflict in translation file
ODOO-1857
Added new fields
Commented fields that are not used anymore that were causing issues
Views and Translations
=> 11.0 foreign trade payment fields ODOO-1857 ODOO-1847

purchase_order_foreign_report/__manifest__.py, purchase_order_foreign_report/report/purchase_order_foreign_report.py, purchase_order_foreign_report/report/purchase_order_foreign_template.xml
Incidence nbr. ODOO-1772
-Translates report lines 'origin'
-added dictionary with translated country names
-updated version
=> [UPD][purchase_order_foreign_report] ODOO-1772

import_dispatch/models/stock_picking.py
=> [FIX][import_dispatch]ODOO-2651

foreign_trade/i18n/es_AR.po, foreign_trade/views/sale_order_view.xml
Incidence nbr./s.: ODOO-2654.
- Add confirm sale button in sales order status
=> [FIX][foreign_trade]

import_dispatch/models/stock_move.py, import_dispatch/models/stock_move_line.py, import_dispatch/models/stock_picking.py, import_dispatch/views/sale_order_views.xml, import_dispatch/views/stock_move_line_views.xml, import_dispatch/views/stock_production_lot_view.xml, stock_picking_lot_extension/models/stock_picking.py
[ADD][import_dispatch][stock_picking_lot_extension]
Incidence nbr./s.: ODOO-1860.
- Changes in comex and receipts in the fields of lot, dispatch and date
=> 11.0 fix import dispatch

import_dispatch/views/sale_order_views.xml
Incidence nbr./s.: ODOO-3069.
- Hide duplicate field in sales
=> [FIX][import_dispatch]

stock_move_lines/models/stock_move_line.py
Incidence nbr./s.: ODOO-3071.
- Add view order button in sales order lines
=> [FIX][stock_move_lines]

foreign_purchase_order_custom/__init__.py
Incidence nbr./s.: ODOO-4060.
- Installation error
=> [ADD][foreign_purchase_order_custom]

foreign_purchase_order_custom/views/purchase_order_view.xml
Incidence nbr./s.: ODOO-4060.
- Remove duplicate field
=> [REM][foreign_purchase_order_custom]

account_invoice_report/__init__.py
Incidence nbr./s.: ODOO-4180.
- Remove the import from the models folder
=> [ADD][account_invoice_report]

sale_templates_mail/data/mail_template_data.xml, sale_templates_mail/data/mail_template_data_impo.xml
=> [ODOO-4012][FIX][sale_templates_mail]

foreign_purchase_order_custom/views/purchase_order_view.xml, purchase_order_foreign_report/data/mail_template_data.xml, purchase_order_foreign_report/data/mail_template_data_impo.xml
Incidence nbr./s.: ODOO-4338
- Field modifications in bookin templates
- Hide field in interventions section
=> [FIX][purchase_order_foreign_report][foreign_purchase_order_custom]

foreign_purchase_order_custom/__init__.py, foreign_purchase_order_custom/__manifest__.py, foreign_purchase_order_custom/models/__init__.py, foreign_purchase_order_custom/models/purchase_order.py, foreign_purchase_order_custom/views/purchase_order_view.xml
Incidence nbr./s.: ODOO-4343
- Change the format of the payment date field
=> [FIX][foreign_purchase_order_custom]

purchase_order_foreign_report/data/mail_template_data.xml
Incidence nbr./s.: ODOO-4338
- fix bug
=> [FIX][purchase_order_foreign_report]

etilfarma_translations_fixes/i18n/es_AR.po
- Add new translation to fields in Inventory
=> [ODOO-4596][UPD][etilfarma_translations_fixes]

foreign_purchase_order/models/purchase_order.py
- Added read-only attribute for date field within comex / purchase order
=> [ODOO-4597][UPD][foreign_purchase_order]

purchase_request_extension/wizard/purchase_request_line_make_purchase_order_view.xml
- Add invisible attribute to keep_description field
=> [ODOO-4748][MOD][purchase_request_extension]

etilfarma_translations_fixes/i18n/es_AR.po
- Translations for Initiatives menu in CRM
=> [ODOO-4722][UPD][etilfarma_translation_fixes]

purchase_request_extension/wizard/purchase_request_line_make_purchase_order_view.xml
- Add invisible attribute to keep_description field
=> [ODOO-4748][UPD][purchase_request_extension]

account_control_validate_invoice/README.rst, account_control_validate_invoice/__init__.py, account_control_validate_invoice/__manifest__.py, account_control_validate_invoice/i18n/es_AR.po, account_control_validate_invoice/models/__init__.py, account_control_validate_invoice/models/product_product.py, account_control_validate_invoice/views/product_logistics_form_view.xml
-Modifications to the packing list report
- new fields in the product form
=> [ODOO-4675][ADD][account_control_validate_invoice]

account_control_validate_invoice/views/product_logistics_form_view.xml
-we modify the gross weight field by adding kg at the end
=> [ODOO-4675][FIX][account_control_validate_invoice]

stock_move_lines/models/stock_move_line.py, stock_move_lines_wait/i18n/es_AR.po, stock_move_lines_wait/models/stock_move.py, stock_move_lines_wait/views/stock_move_view.xml
- Added new fields, translations and field orders
=> [ODOO-4570][UPD][stock_move_lines_wait] 

account_control_validate_invoice/models/stock_move.py, foreign_trade/i18n/es_AR.po
- Problems in weight calculations
- Tranlations to terms
=> [ODOO-4676][FIX][account_control_validate_invoice][foreing_trade] 

stock_move_lines/models/stock_move_line.py, stock_move_lines_wait/models/stock_move.py
- remaining_amount calculation fix
=> [ODOO-4570][FIX][stock_move_lines_wait] 

stock_move_lines_wait/views/stock_move_view.xml
=> [ODOO-4570][REM][stock_move_lines_wait]

account_validate_perception_control/README.rst, account_validate_perception_control/__init__.py, account_validate_perception_control/__manifest__.py, account_validate_perception_control/i18n/es_AR.po, account_validate_perception_control/models/__init__.py, account_validate_perception_control/models/account_invoice.py
-Edit the validate button so that it can only be activated if the validate control was executed.
=> [ODOO-4569][IMP][account_validate_perception_control]

foreign_trade/data/ir_sequence.xml, foreign_trade/models/stock_picking.py, foreign_trade/report/sale_order_template.xml, foreign_trade/views/packing_list_report.xml, foreign_trade/views/stock_picking_form_view.xml
- English and Spanish Packing List Report Settings
=> [ODOO-4677][UPD][foreign_trade]

account_control_validate_invoice/__manifest__.py, account_control_validate_invoice/i18n/es_AR.po, account_control_validate_invoice/models/__init__.py, account_control_validate_invoice/models/stock_move.py, account_control_validate_invoice/views/product_logistics_form_view.xml, account_control_validate_invoice/views/stock_picking_view.xml, foreign_trade/i18n/es_AR.po
- Account_control_validate_invoice module for field calculations in stock picking product lines
=> [ODOO-4676][ADD][account_control_validate_invoice] 

foreign_trade/models/stock_picking.py
- Fix in create method of Stock Picking model
=> [ODOO-4570][FIX][foreign_trade]

account_invoice_report/models/account_invoice.py, l10n_aeroo_einvoice_custom_output/models/account_invoice.py
- Fix in invoice report with customer_purchase_order field
=> [ODOO-4712][FIX][account_invoice_report][l10n_aeroo_einvoice_custom_output] 

stock_move_lines_wait/models/stock_move.py, stock_move_lines_wait/views/stock_move_view.xml
=> [ODOO-4570][IMP][stock_move_lines_wait]

stock_move_lines_wait/models/stock_move.py
Fix in rec in computed remainig_amount field
=> [ODOO-4570][FIX][stock_move_lines_wait]

foreign_trade/views/packing_list_report.xml
- Improvements in the packing report
=> [ODOO-4677][IMP][foreign_trade]

foreign_trade/i18n/es_AR.po
- Translations to proforma invoice report
=> [ODOO-4780][IMP][foreign_trade]

foreign_trade/data/ir_sequence.xml, foreign_trade/i18n/es_AR.po, foreign_trade/models/stock_picking.py, foreign_trade/report/sale_order_template.xml, foreign_trade/report/sale_report.xml, foreign_trade/views/packing_list_report.xml, foreign_trade/views/stock_picking_form_view.xml, stock_move_lines_wait/i18n/es_AR.po, stock_move_lines_wait/models/stock_move.py, stock_move_lines_wait/views/stock_move_view.xml
- Improvements view Lines of orders
- Modify proforma name in sales report
- Packing list report in English and Spanish - Modifications
=> [ODOO-4570][ODOO-4780][ODOO-4677][IMP][foreign_trade][stock_move_lines_wait]

account_validate_perception_control/__manifest__.py, account_validate_perception_control/views/account_validate_perception_control.xml
-Add the perception control to the vendor invoice
=> [ODOO-6007][IMP][account_validate_perception_control]

account_validate_perception_control/__manifest__.py, account_validate_perception_control/views/account_validate_perception_control.xml
-Add the perception control to the vendor invoice.
=>  [ODOO-6007][IMP][account_validate_perception_control]
